### ISSUE TITLE
npm start fails : app.js is missing

### ISSUE THREAD

**Issue by navneetccna** [codekeyz/angular-electron-adminlte#1]
91% additional asset processing scripts-webpack-plugin✖ ｢wdm｣: Error: ENOENT: no such file or directory, open '/projects/angular-electron-adminlte/src/assets/app.js'
    at Object.fs.openSync (fs.js:545:3)
    at Object.fs.readFileSync (fs.js:451:33)
    at Storage.provideSync (/home/owner/projects/angular-electron-adminlte/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:98:13)
    at CachedInputFileSystem.readFileSync (/home/owner/projects/angular-electron-adminlte/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:259:32)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/home/owner/projects/angular-electron-adminlte/node_modules/@ngtools/webpack/src/webpack-input-host.js:35:51)
    at Observable._trySubscribe (/home/owner/projects/angular-electron-adminlte/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/home/owner/projects/angular-electron-adminlte/node_modules/rxjs/internal/Observable.js:30:22)
    at SyncDelegateHost._doSyncCall (/home/owner/projects/angular-electron-adminlte/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:22:20)
    at SyncDelegateHost.read (/home/owner/projects/angular-electron-adminlte/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:49:21)
    at WebpackCompilerHost.readFileBuffer (/home/owner/projects/angular-electron-adminlte/node_modules/@ngtools/webpack/src/compiler_host.js:115:44)
    at VirtualFileSystemDecorator.readFile (/home/owner/projects/angular-electron-adminlte/node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:38:54)
    at Promise (/home/owner/projects/angular-electron-adminlte/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/scripts-webpack-plugin.js:92:49)
    at new Promise (<anonymous>)
    at scripts.map.fullPath (/home/owner/projects/angular-electron-adminlte/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/scripts-webpack-plugin.js:91:24)
    at Array.map (<anonymous>)
    at hook (/home/owner/projects/angular-electron-adminlte/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/scripts-webpack-plugin.js:90:43)

**Comment by codekeyz** [comment]
@navneetccna Can you provide the steps to reproduce this error; that will make it easy to fix.

**Comment by navneetccna** [comment]
clone the repo
npm install
npm start
As given in the readme file

**Comment by codekeyz** [comment]
@navneetccna I have found & fixed the bug. Do check the repo again. It should work this time around.

**Comment by navneetccna** [comment]
Still not working 
now adminlte.js missing

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 10% building modules 6/6 modules 0 activeℹ ｢wdm｣: wait until bundle finished: /     
 91% additional asset processing scripts-webpack-plugin✖ ｢wdm｣: Error: ENOENT: no such file or directory, open '/home/owner/projects/angular-electron-adminlte/src/assets/dist/js/adminlte.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Storage.provideSync (/home/owner/projects/angular-electron-adminlte/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:98:13)
    at CachedInputFileSystem.readFileSync (/home/owner/projects/angular-electron-adminlte/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:259:32)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/home/owner/projects/angular-electron-adminlte/node_modules/@ngtools/webpack/src/webpack-input-host.js:35:51)
    at Observable._trySubscribe (/home/owner/projects/angular-electron-adminlte/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/home/owner/projects/angular-electron-adminlte/node_modules/rxjs/internal/Observable.js:30:22)
    at SyncDelegateHost._doSyncCall (/home/owner/projects/angular-electron-adminlte/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:22:20)
    at SyncDelegateHost.read (/home/owner/projects/angular-electron-adminlte/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:49:21)
    at WebpackCompilerHost.readFileBuffer (/home/owner/projects/angular-electron-adminlte/node_modules/@ngtools/webpack/src/compiler_host.js:115:44)
    at VirtualFileSystemDecorator.readFile (/home/owner/projects/angular-electron-adminlte/node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:38:54)
    at Promise (/home/owner/projects/angular-electron-adminlte/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/scripts-webpack-plugin.js:92:49)
    at new Promise (<anonymous>)
    at scripts.map.fullPath (/home/owner/projects/angular-electron-adminlte/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/scripts-webpack-plugin.js:91:24)
    at Array.map (<anonymous>)
    at hook (/home/owner/projects/angular-electron-adminlte/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/scripts-webpack-plugin.js:90:43)

**Comment by codekeyz** [comment]
@navneetccna Sorry i had that file ignored in my gitignore file. Please do check this around, it works
